apiVersion: v1
kind: Pod
metadata:
  name: jay-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 2
    env:
    - name: DB_CONNECT
      valueFrom:
        configMapKeyRef:
          name: jay-env
          key: DB_URL
